# Generated by Django 3.1.4 on 2021-06-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auto_20210607_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='catergory',
            new_name='category',
        ),
    ]
