# Generated by Django 3.2.3 on 2021-07-13 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='cutomer',
            new_name='customer',
        ),
    ]
